### ISSUE TITLE
Import/Export profile as `.csv` or `.json`

### ISSUE THREAD

**Issue by mrodz** [mrodz/fieldz-desktop#111]
Functionality to import and export a profile as a CSV file

- [ ] Transform the data inside a profile to an exportable file type
- [ ] UI to export and import data
- [ ] Publish profile to the internet
