### ISSUE TITLE
Add profile switching context

### ISSUE THREAD

**Issue by mrodz** [mrodz/fieldz-desktop#112]
- [x] #116
- [x] API and bridge functions
- [x] #118
- [x] Testing
  - [x] Error message for OS reserved file names
  - [x] All expected errors
  - [x] Seamless execution, implementation test
