### ISSUE TITLE
[URGENT] App is broken because my firebase functions lost their URLs

### ISSUE THREAD

**Issue by mrodz** [mrodz/fieldz-desktop#131]
My Google Cloud account got frozen because I missed a payment, and I lost the names of all my functions. When my account was reenabled, I was assigned entirely different names for all these functions.

The following have been renamed:
- [x] `env(QUOTA_SERVER_URL)`
- [x] `env(SCHEDULER_SERVER_URL`
- [x] `env(AUTH_SERVER_URL)`
- [x] `env(TWITTER_REQUEST_TOKEN_URL)`
- [x] `env(TWITTER_OAUTH_CREDENTIAL_URL)`

**Comment by mrodz** [comment]
I've updated my environment variables and the GitHub secrets.
