### ISSUE TITLE
Coach Conflict - Database & CRUD

### ISSUE THREAD

**Issue by mrodz** [mrodz/fieldz-desktop#88]
### CRUD Points:
<img width="383" alt="image" src="https://github.com/mrodz/fieldz-desktop/assets/79176075/0a679674-6455-4ff5-89a3-5c79bc01cc82">

### Tasks
- [x] New migration and tables
  - [X] Table: `CoachConflict`
  - [X] Table: `CoachConflictTeamJoin`
- [x] Error Enums
- [x] Input Structs
- [x] DB Client - CRUD for Coach Conflict Mapping
  - [x] `READ` Conflicts belonging to region 
  - [x] `CREATE` Conflict
  - [x] `DELETE` Conflict
  - [x] `UPDATE` Conflict - Team Add/Remove
  - [x] `UPDATE` Conflict - Coach Name
- [x] Update `index.ts` with new type declarations
- [x] Extend all of the `// TODO`  functions in JS land to call into new Tauri commands

**Comment by mrodz** [comment]
Closed by #92
